# Generated by Django 3.2.4 on 2021-06-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veterinaria_nombre', models.CharField(max_length=200)),
                ('veterinaria_direcion', models.CharField(max_length=200)),
                ('veterinaria_creacion', models.DateTimeField(verbose_name='fecha de Publicacion')),
            ],
        ),
        migrations.DeleteModel(
            name='Verterinaria',
        ),
    ]
