# Generated by Django 3.2.4 on 2021-06-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210612_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinaria',
            name='veterinaria_descripcion',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
